version: '3'

services:
  database:
    image: mongo

  reviews:
    build: service-chris/
    depends_on:
      - 'database'
    ports:
      - '3002:3002'

  proxy:
    build: proxy/
    ports:
      - '3010:3010'
