version: '3'

services:
  reviews:
    build: service-chris/
    depends_on:
      - 'database'
    ports:
      - '3002:8080'

  proxy:
    build: proxy/
    ports:
      - '3010:8080'

  database:
    image: mongo:latest