version: '3'

services:
  database:
    image: mongo

  reviews:
    build: service-chris/
    depends_on:
      - 'database'
    ports:
      - '3002:3002'

  # carousel:
  #   build: service-dannyhannyford/
  #   depends_on:
  #     - 'database'
  #   ports:
  #     - '3007:3007'
